# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160826_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
