# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='movie',
        ),
        migrations.AddField(
            model_name='time',
            name='movie',
            field=models.ManyToManyField(related_name='shows', to='main.Movie'),
        ),
        migrations.RemoveField(
            model_name='time',
            name='theater',
        ),
        migrations.AddField(
            model_name='time',
            name='theater',
            field=models.ManyToManyField(related_name='shows', to='main.Theather'),
        ),
    ]
